# -*- coding: utf-8 -*-
"""U-Net.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19-PcnVMWSjVS-CXIk17l2-5ka454hubV
"""

# ==========================================
# 1. SETUP & LIBRARIES
# ==========================================
!pip install segmentation-models-pytorch albumentations

import os
import cv2
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from google.colab import drive
import shutil
import segmentation_models_pytorch as smp
import albumentations as A
from albumentations.pytorch import ToTensorV2
from tqdm import tqdm
import matplotlib.pyplot as plt

# Mount Drive
print("🔄 Mounting Drive...")
drive.mount('/content/drive')

# PATHS
DRIVE_FOLDER = "/content/drive/MyDrive/Final_Project_Phase2"
ZIP_FILE = os.path.join(DRIVE_FOLDER, "unet_data.zip")
DATA_DIR = "/content/dataset"

# ==========================================
# 2. EXTRACT DATA
# ==========================================
if not os.path.exists(DATA_DIR):
    print("📂 Extracting Dataset...")
    shutil.unpack_archive(ZIP_FILE, DATA_DIR)
else:
    print("✅ Dataset already extracted.")

# Check structure
IMG_DIR = os.path.join(DATA_DIR, 'unet_images')
MASK_DIR = os.path.join(DATA_DIR, 'unet_masks')

# ==========================================
# 3. DATASET CLASS & AUGMENTATIONS
# ==========================================
class PolypDataset(Dataset):
    def __init__(self, img_dir, mask_dir, subset='train', transform=None):
        self.img_path = os.path.join(img_dir, subset)
        self.mask_path = os.path.join(mask_dir, subset)
        self.transform = transform
        self.images = os.listdir(self.img_path)

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_name = self.images[idx]

        # Load Image
        img = cv2.imread(os.path.join(self.img_path, img_name))
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        # Load Mask
        mask_name = img_name
        mask = cv2.imread(os.path.join(self.mask_path, mask_name), cv2.IMREAD_GRAYSCALE)

        # Binary mask (0 or 1)
        _, mask = cv2.threshold(mask, 127, 1, cv2.THRESH_BINARY)

        if self.transform:
            augmented = self.transform(image=img, mask=mask)
            img = augmented['image']
            mask = augmented['mask']

        return img, mask.long()

# Augmentations
train_transform = A.Compose([
    A.Resize(256, 256),
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.5),
    A.Rotate(limit=30, p=0.5),
    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
    ToTensorV2()
])

val_transform = A.Compose([
    A.Resize(256, 256),
    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
    ToTensorV2()
])

# Loaders
train_dataset = PolypDataset(IMG_DIR, MASK_DIR, subset='train', transform=train_transform)
val_dataset = PolypDataset(IMG_DIR, MASK_DIR, subset='val', transform=val_transform)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True, num_workers=2)
val_loader = DataLoader(val_dataset, batch_size=16, shuffle=False, num_workers=2)

print(f"✅ Data Loaded: {len(train_dataset)} Train, {len(val_dataset)} Val images")

# ==========================================
# 4. MODEL SETUP
# ==========================================
model = smp.Unet(
    encoder_name="resnet34",
    encoder_weights="imagenet",
    in_channels=3,
    classes=1,
    activation=None
)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
model.to(DEVICE)

loss_fn = smp.losses.DiceLoss(smp.losses.BINARY_MODE, from_logits=True)
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-5)

# ==========================================
# 5. TRAINING LOOP (With Graph Tracking)
# ==========================================
best_val_loss = float('inf')
patience = 7
counter = 0

# Lists to store metrics for the graph
history = {'train_loss': [], 'val_loss': []}

print(" Starting Training...")

for epoch in range(50):
    model.train()
    train_loss = 0

    for imgs, masks in tqdm(train_loader, desc=f"Epoch {epoch+1}"):
        imgs, masks = imgs.to(DEVICE), masks.to(DEVICE)

        optimizer.zero_grad()
        logits = model(imgs)
        loss = loss_fn(logits, masks)
        loss.backward()
        optimizer.step()
        train_loss += loss.item()

    # Validation
    model.eval()
    val_loss = 0
    with torch.no_grad():
        for imgs, masks in val_loader:
            imgs, masks = imgs.to(DEVICE), masks.to(DEVICE)
            logits = model(imgs)
            loss = loss_fn(logits, masks)
            val_loss += loss.item()

    avg_train_loss = train_loss / len(train_loader)
    avg_val_loss = val_loss / len(val_loader)

    # Store history
    history['train_loss'].append(avg_train_loss)
    history['val_loss'].append(avg_val_loss)

    print(f"   Train Loss: {avg_train_loss:.4f} | Val Loss: {avg_val_loss:.4f}")

    if avg_val_loss < best_val_loss:
        best_val_loss = avg_val_loss
        torch.save(model.state_dict(), "best_unet.pth")
        print("    Model Improved. Saved 'best_unet.pth'")
        counter = 0
    else:
        counter += 1
        if counter >= patience:
            print("🛑 Early Stopping triggered.")
            break

# ==========================================
# 6. GENERATE RESULTS GRAPHS & RANDOM SAMPLES
# ==========================================
import random

print("\n Generating Graphs...")

# 1. Plot Loss Curve (Only needs to run once, but safe to run again)
if not os.path.exists('training_loss.png'):
    plt.figure(figsize=(10, 5))
    plt.plot(history['train_loss'], label='Train Loss')
    plt.plot(history['val_loss'], label='Val Loss')
    plt.title('Training vs Validation Loss')
    plt.xlabel('Epochs')
    plt.ylabel('Dice Loss')
    plt.legend()
    plt.grid(True)
    plt.savefig('training_loss.png')
    print("   -> Saved 'training_loss.png'")

# 2. Generate RANDOM Sample Prediction
model.load_state_dict(torch.load("best_unet.pth"))
model.eval()

# --- NEW: Pick a random index from the entire validation set ---
random_idx = random.randint(0, len(val_dataset) - 1)
print(f"   🎲 Visualizing Random Image Index: {random_idx}")

# Get single sample directly from dataset
img_tensor, mask_tensor = val_dataset[random_idx]

# Add batch dimension (C, H, W) -> (1, C, H, W) for the model
input_tensor = img_tensor.unsqueeze(0).to(DEVICE)

with torch.no_grad():
    logits = model(input_tensor)
    pred_tensor = torch.sigmoid(logits) > 0.5
    # Remove batch dim for plotting: (1, 1, H, W) -> (H, W)
    pred_np = pred_tensor[0, 0].cpu().numpy()

# Process Original Image for Display (Un-normalize)
# (3, H, W) -> (H, W, 3)
img_np = img_tensor.permute(1, 2, 0).cpu().numpy()
mean = np.array([0.485, 0.456, 0.406])
std = np.array([0.229, 0.224, 0.225])
img_np = std * img_np + mean
img_np = np.clip(img_np, 0, 1)

# Process Ground Truth Mask
mask_np = mask_tensor.cpu().numpy()

# Plot side-by-side
plt.figure(figsize=(12, 4))
plt.subplot(1, 3, 1)
plt.imshow(img_np)
plt.title(f"Original Image (ID: {random_idx})")
plt.axis('off')

plt.subplot(1, 3, 2)
plt.imshow(mask_np, cmap='gray')
plt.title("Ground Truth Mask")
plt.axis('off')

plt.subplot(1, 3, 3)
plt.imshow(pred_np, cmap='gray')
plt.title("AI Prediction")
plt.axis('off')

# Save with a unique name if you want to keep them, or overwrite
filename = f'sample_prediction_{random_idx}.png'
plt.savefig(filename)
print(f"   -> Saved '{filename}'")
plt.show() # Show immediately in Colab

# ==========================================
# 7. SAVE EVERYTHING TO DRIVE
# ==========================================
print("\n📦 Saving all artifacts to Google Drive...")
artifacts = ['best_unet.pth', 'training_loss.png', 'sample_prediction.png']
results_folder = os.path.join(DRIVE_FOLDER, "Segmentation_Results")
os.makedirs(results_folder, exist_ok=True)

for file in artifacts:
    if os.path.exists(file):
        shutil.copy(file, os.path.join(results_folder, file))
        print(f"   Saved: {file}")

print(f"\nCheck the 'Segmentation_Results' folder in your Drive.")

# ==========================================
# PHASE 2.5: FINE-TUNING (Run in New Cell)
# ==========================================
import os
import cv2
import numpy as np
import torch
import segmentation_models_pytorch as smp
import albumentations as A
from albumentations.pytorch import ToTensorV2
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm
import shutil

# 1. SETUP PATHS
# We assume data is already at /content/dataset from the previous run
DATA_DIR = "/content/dataset"
IMG_DIR = os.path.join(DATA_DIR, 'unet_images')
MASK_DIR = os.path.join(DATA_DIR, 'unet_masks')
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# 2. DEFINE AGGRESSIVE AUGMENTATIONS
print(" Applying Aggressive Augmentations...")
train_transform = A.Compose([
    A.Resize(256, 256),
    # Shape/Geometry
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.5),
    A.Rotate(limit=45, p=0.7),
    A.ElasticTransform(alpha=1, sigma=50, alpha_affine=50, p=0.3),
    A.GridDistortion(p=0.3),
    # Color/Noise
    A.RandomBrightnessContrast(p=0.5),
    A.GaussNoise(var_limit=(10.0, 50.0), p=0.3),
    A.CoarseDropout(max_holes=8, max_height=20, max_width=20, p=0.2),
    # Normalize
    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
    ToTensorV2()
])

val_transform = A.Compose([
    A.Resize(256, 256),
    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
    ToTensorV2()
])

# 3. RE-CREATE DATASETS (With new transforms)
# We redefine the class to ensure it uses the new 'train_transform'
class PolypDataset(Dataset):
    def __init__(self, img_dir, mask_dir, subset='train', transform=None):
        self.img_path = os.path.join(img_dir, subset)
        self.mask_path = os.path.join(mask_dir, subset)
        self.transform = transform
        self.images = os.listdir(self.img_path)
    def __len__(self): return len(self.images)
    def __getitem__(self, idx):
        img_name = self.images[idx]
        img = cv2.imread(os.path.join(self.img_path, img_name))
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        mask = cv2.imread(os.path.join(self.mask_path, img_name), cv2.IMREAD_GRAYSCALE)
        _, mask = cv2.threshold(mask, 127, 1, cv2.THRESH_BINARY)
        if self.transform:
            augmented = self.transform(image=img, mask=mask)
            img = augmented['image']
            mask = augmented['mask']
        return img, mask.long()

train_dataset = PolypDataset(IMG_DIR, MASK_DIR, subset='train', transform=train_transform)
val_dataset = PolypDataset(IMG_DIR, MASK_DIR, subset='val', transform=val_transform)
train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True, num_workers=2)
val_loader = DataLoader(val_dataset, batch_size=16, shuffle=False, num_workers=2)

# 4. LOAD THE BEST MODEL FROM PREVIOUS STEP
# We look for the file locally first
local_best_model = "best_unet.pth"

model = smp.Unet(encoder_name="resnet34", encoder_weights=None, in_channels=3, classes=1)

if os.path.exists(local_best_model):
    print(f" Loading weights from local session: {local_best_model}")
    model.load_state_dict(torch.load(local_best_model, map_location=DEVICE))
else:
    print(" Local model not found. Using random weights (Not ideal).")

model.to(DEVICE)

# 5. FINE-TUNING SETUP
# Lower learning rate (1e-5) to gently polish the weights
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-5, weight_decay=1e-5)
loss_fn = smp.losses.DiceLoss(smp.losses.BINARY_MODE, from_logits=True)

# 6. TRAINING LOOP
print("Starting Fine-Tuning (30 Epochs)...")
best_val_loss = float('inf')
patience = 10
counter = 0

for epoch in range(30):
    model.train()
    train_loss = 0

    for imgs, masks in tqdm(train_loader, desc=f"Fine-Tune Epoch {epoch+1}"):
        imgs, masks = imgs.to(DEVICE), masks.to(DEVICE)
        optimizer.zero_grad()
        logits = model(imgs)
        loss = loss_fn(logits, masks)
        loss.backward()
        optimizer.step()
        train_loss += loss.item()

    # Validation
    model.eval()
    val_loss = 0
    with torch.no_grad():
        for imgs, masks in val_loader:
            imgs, masks = imgs.to(DEVICE), masks.to(DEVICE)
            logits = model(imgs)
            loss = loss_fn(logits, masks)
            val_loss += loss.item()

    avg_train_loss = train_loss / len(train_loader)
    avg_val_loss = val_loss / len(val_loader)
    print(f"   Train Loss: {avg_train_loss:.4f} | Val Loss: {avg_val_loss:.4f}")

    # Save Best Fine-Tuned Model
    if avg_val_loss < best_val_loss:
        best_val_loss = avg_val_loss
        torch.save(model.state_dict(), "best_unet_finetuned.pth")
        print(" Improved! Saved 'best_unet_finetuned.pth'")
        counter = 0
    else:
        counter += 1
        if counter >= patience:
            print("Early Stopping.")
            break

# 7. SAVE TO DRIVE
print("\n Saving Final Model to Drive...")
# Define Drive Path
DRIVE_FOLDER = "/content/drive/MyDrive/Final_Project_Phase2"
dest_path = os.path.join(DRIVE_FOLDER, "Segmentation_Results", "unet_finetuned_best.pth")
os.makedirs(os.path.dirname(dest_path), exist_ok=True)

if os.path.exists("best_unet_finetuned.pth"):
    shutil.copy("best_unet_finetuned.pth", dest_path)
    print(f" Success! Saved to: {dest_path}")
else:
    print(" No improvement found during fine-tuning.")

# ==========================================
# 7. GENERATE RESULTS FOR FINE-TUNED MODEL
# ==========================================
import random
import matplotlib.pyplot as plt

# Check if model exists before loading
model_filename = "best_unet_finetuned.pth"
if not os.path.exists(model_filename):
    print(f"Error: Could not find '{model_filename}'. Did training finish?")
else:
    print(f"\nVisualizing Results from: {model_filename}")

    # Load the FINE-TUNED model
    model.load_state_dict(torch.load(model_filename, map_location=DEVICE))
    model.eval()

    # --- Pick a random index from the validation set ---
    random_idx = random.randint(0, len(val_dataset) - 1)
    print(f"   Visualizing Random Image Index: {random_idx}")

    # Get single sample
    img_tensor, mask_tensor = val_dataset[random_idx]

    # Add batch dimension (C, H, W) -> (1, C, H, W)
    input_tensor = img_tensor.unsqueeze(0).to(DEVICE)

    with torch.no_grad():
        logits = model(input_tensor)
        pred_tensor = torch.sigmoid(logits) > 0.5
        pred_np = pred_tensor[0, 0].cpu().numpy()

    # Process Original Image (Un-normalize)
    img_np = img_tensor.permute(1, 2, 0).cpu().numpy()
    mean = np.array([0.485, 0.456, 0.406])
    std = np.array([0.229, 0.224, 0.225])
    img_np = std * img_np + mean
    img_np = np.clip(img_np, 0, 1)

    # Process Ground Truth Mask
    mask_np = mask_tensor.cpu().numpy()

    # Plot side-by-side
    plt.figure(figsize=(12, 4))

    plt.subplot(1, 3, 1)
    plt.imshow(img_np)
    plt.title(f"Original (ID: {random_idx})")
    plt.axis('off')

    plt.subplot(1, 3, 2)
    plt.imshow(mask_np, cmap='gray')
    plt.title("Ground Truth")
    plt.axis('off')

    plt.subplot(1, 3, 3)
    plt.imshow(pred_np, cmap='gray')
    plt.title("Fine-Tuned Prediction")
    plt.axis('off')

    plt.tight_layout()
    plt.show()